# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: karlinskys
email: ejkarlinsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Established in August 2014. Going for broke in the Bay Area ever since.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karlinskys.com" # the base hostname & protocol for your site
twitter_username: ejkarlinsky
github_username:  ejkarlinsky

# Build settings
markdown: kramdown
